### ISSUE TITLE
Component: create sidebar (vertical menu)

### ISSUE THREAD

**Issue by StanleySathler** [HeiderMaciel/gerir-me#4]
Create the sidebar component, a vertical menu which goals to reduce navigation between pages through buttons.

**Comment by StanleySathler** [comment]
After so much research, it is known that build the sidebar with items and subitems wouldn't be possible using Lift's native SiteMap Builder.

We may try another approach, such as request all menu items while user is still logging in, save 'em (LocalStorage is enough) and build the sidebar using JavaScript.

Build the menu using Lift's Snippet are out of scope because we don't want to make a lot of requests only to build a menu.

**Comment by StanleySathler** [comment]
The Sidebar is now created. Menu items are loaded from Local Storage, while these are saved when the user is logging in.

So, what's the plan? When the user clicks on "login" button, for now, the request sends a response with some information. This response should respond with available menus as well.

Do you wanna try it, @rigelferreira?

In the **loginController.js** file, at line 29, there is the method which saves the menu options. As you can see at line 14, `response.menus` should contain the menu.

**Comment by HeiderMaciel** [comment]
@StanleySathler , I can push this in dev environment.
But the branch configured in test environment is test. This is correct?
root@li467-165:~/app/gerir-me# git status
On branch test
Your branch is up-to-date with 'origin/test'.
nothing to commit, working directory clean

**Comment by StanleySathler** [comment]
@HeiderMaciel, `test` branch holds only those features which are ready to be merged and pushed to the production environment, but still need some user tests.

Sidebar is being developed in `redesign-sidebar` branch. If you wanna test it, there are two different ways:
* On the test environment, you can pull the branch directly: `$ git pull origin redesign-sidebar`
* On your local machine, you can just navigate through branches. To change to the sidebar's one, just type `$ git fetch && git checkout redesign-sidebar`.

But remember: sidebar is not ready yet and can not be merged to the master.
